FROM mcr.microsoft.com/playwright:focal

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install -qq -y build-essential nodejs yarn

WORKDIR /app
COPY . .

WORKDIR /app/Tests
RUN ["yarn", "install"]

CMD ["sh", "startup.sh"]
