FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine as backend

RUN apt-get update && \
    apt-get install -qq -y build-essential \
    libpq-dev

# Install dotnet tools
ENV PATH $PATH:/root/.dotnet/tools
RUN dotnet tool install --global dotnet-ef

WORKDIR /app/Dotnet
COPY ./Dotnet/. .
WORKDIR /app/Dotnet/EntryPoint

ENV ASPNETCORE_URLS=http://*:5000
ENV BACKEND=true

CMD ["dotnet", "watch", "run" ]
