FROM python:3

RUN apt install libpango-1.0-0 libpangoft2-1.0-0

RUN mkdir -p /var/docs
RUN mkdir -p /var/docs/src/docs/shared
RUN mkdir -p /var/docs/src/docs/modules
RUN mkdir -p /var/docs/src/docs/shared/Docs
RUN mkdir -p /var/docs/src/docs/modules/Docs

COPY . /var/docs
WORKDIR /var/docs

RUN pip install -r ./requirements.txt

EXPOSE 8000

CMD ["sh", "docker-startup.sh"]
