FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine3.19 as backend
WORKDIR /app
COPY ./Main .
WORKDIR /app/EntryPoint
RUN dotnet publish -c Release -o out

RUN apk add git
WORKDIR /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine3.19 as runtime
WORKDIR /app

RUN wget https://code.hoppinger.com/automation/ca-certs/-/raw/master/elasticsearch/cacert.pem --no-check-certificate -O es-cacert.pem

COPY --from=backend /app/EntryPoint/out .
CMD ["dotnet", "Zovio.dll", "hangfire"]
