FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine as backend

RUN apt-get update && \
    apt-get install -qq -y build-essential \
    libpq-dev

WORKDIR /app/Dotnet
COPY ./Dotnet/. .
WORKDIR /app/Dotnet/EntryPoint

ENV HANGFIRE=true

CMD ["dotnet", "watch", "run", "hangfire"]
