GET http://localhost:5000/swagger/v1/swagger.json HTTP/1.1
#####

GET http://localhost:5000/ABEvents?skip=0&take=100 HTTP/1.1
content-type: application/json
#####

GET http://localhost:5000/AEvents?skip=0&take=100 HTTP/1.1
content-type: application/json
#####

GET http://localhost:5000/BEvents?skip=0&take=100 HTTP/1.1
content-type: application/json
#####

POST http://localhost:5000/ABs HTTP/1.1
content-type: application/json

{"abId":"00000000-0000-0000-0000-000000000000","aCount":0,"bCount":0,"aFailCount":0,"bFailCount":0}
#####

POST http://localhost:5000/ABEvents HTTP/1.1
content-type: application/json

{"$type":"BEvent","abId":"0a5d8518-89ac-42bb-87f3-b38096c517d7","abEventId":"00000000-0000-0000-0000-000000000000", "BStep":10 }
#####

POST http://localhost:5000/ABEvents HTTP/1.1
content-type: application/json

{"$type":"AEvent","abId":"0a5d8518-89ac-42bb-87f3-b38096c517d7","abEventId":"00000000-0000-0000-0000-000000000000", "AStep":10 }
#####

GET http://localhost:5000/ABs?skip=0&take=100 HTTP/1.1
content-type: application/json
#####
